spring.application.name=journalApp
spring.data.mongodb.uri=mongodb+srv://arun:arun123@cluster0.neqykvx.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true